sudo: false

language: node_js

node_js:  
  - 10
  - 12

os:
  - osx
  - linux

cache:
  yarn: true  

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn install

script:
  - yarn run test

after_success:
  - yarn coveralls